# Generated by Django 4.1.1 on 2022-09-26 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_user_name', models.CharField(blank=True, max_length=300, null=True)),
                ('host_user_id', models.CharField(blank=True, max_length=300, null=True)),
                ('host_user_email', models.CharField(blank=True, max_length=300, null=True)),
                ('event_name', models.CharField(blank=True, max_length=300, null=True)),
                ('event_date', models.CharField(blank=True, max_length=300, null=True)),
                ('number_of_members_allowes', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=300, null=True)),
                ('user_id', models.CharField(blank=True, max_length=300, null=True)),
                ('user_email', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.CharField(blank=True, max_length=300, null=True)),
                ('number_of_members', models.CharField(blank=True, max_length=300, null=True)),
                ('leader_user_name', models.CharField(blank=True, max_length=300, null=True)),
                ('leader_user_id', models.CharField(blank=True, max_length=300, null=True)),
                ('leader_email', models.CharField(blank=True, max_length=300, null=True)),
                ('event_participated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.events')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='host_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.host'),
        ),
    ]
