# Generated by Django 4.1.1 on 2022-09-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_host_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='names_of_team_members',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
