# Generated by Django 4.1.1 on 2022-09-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_teams_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='event_participated',
        ),
        migrations.DeleteModel(
            name='events',
        ),
    ]
