# Generated by Django 4.1.1 on 2022-09-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_remove_teams_event_participated_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_user_name', models.CharField(blank=True, max_length=300, null=True)),
                ('host_user_id', models.CharField(blank=True, max_length=300, null=True)),
                ('host_user_email', models.CharField(blank=True, max_length=300, null=True)),
                ('event_name', models.CharField(blank=True, max_length=300, null=True)),
                ('event_date', models.CharField(blank=True, max_length=300, null=True)),
                ('number_of_members_allowes', models.CharField(blank=True, max_length=300, null=True)),
                ('names_of_team_members', models.CharField(blank=True, max_length=1000, null=True)),
                ('host_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.host')),
            ],
        ),
    ]
