# Generated by Django 4.1.1 on 2022-09-26 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='event_participated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.events'),
        ),
    ]
