# Generated by Django 4.1.1 on 2022-09-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_alter_teams_leader_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='names_of_team_members',
        ),
    ]
