# Generated by Django 4.1.1 on 2022-09-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_remove_events_names_of_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='names_of_team_members',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
