# Generated by Django 4.1.1 on 2022-09-26 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_remove_events_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='host_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.host'),
        ),
    ]
