# Generated by Django 4.1.1 on 2022-09-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_razorpay_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpay_credentials',
            name='host_user_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='razorpay_credentials',
            name='host_user_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
