# Generated by Django 4.1.1 on 2022-09-27 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_razorpay_credentials_host_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='number_of_members_allowes',
            new_name='number_of_members_allowed',
        ),
        migrations.AddField(
            model_name='events',
            name='type_of_event',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=300, null=True)),
                ('player_user_name', models.CharField(blank=True, max_length=300, null=True)),
                ('player_user_id', models.CharField(blank=True, max_length=300, null=True)),
                ('player_email', models.CharField(blank=True, max_length=300, null=True)),
                ('player_phone_number', models.CharField(blank=True, max_length=300, null=True)),
                ('event_participated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.events')),
            ],
        ),
    ]
