# Generated by Django 4.1.1 on 2022-09-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_rename_number_of_members_allowes_events_number_of_members_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='payment_id',
            field=models.CharField(blank=True, default='rzp_test_8IrJ4WuGJAF95Q', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='payment_key',
            field=models.CharField(blank=True, default='qxjiUvDTYTccH9AdqGWEAWT5', max_length=30, null=True),
        ),
    ]
