# Generated by Django 4.1.1 on 2022-09-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_events_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fees',
            field=models.CharField(blank=True, default='upaid', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='fees',
            field=models.CharField(blank=True, default='upaid', max_length=30, null=True),
        ),
    ]
