# Generated by Django 4.1.1 on 2022-09-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_player_fees_alter_events_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='name_of_members',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
