# Generated by Django 4.1.1 on 2022-09-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0019_events_discription_events_rules_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='names_of_team_members',
        ),
    ]
