# Generated by Django 4.1.1 on 2022-09-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0021_remove_events_fees_teams_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_date',
            new_name='closing_event_date',
        ),
        migrations.AddField(
            model_name='events',
            name='opening_event_date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
