# Generated by Django 4.1.1 on 2022-09-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0023_alter_events_host_name_alter_host_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='leader_user_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
