# Generated by Django 4.1.1 on 2022-09-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0024_alter_teams_leader_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fees',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='fees',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
