# Generated by Django 4.1.1 on 2022-09-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0027_delete_razorpay_credentials_remove_events_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='fees',
        ),
        migrations.AddField(
            model_name='events',
            name='fees',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='leader_phone_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
