# Generated by Django 4.1.1 on 2022-09-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0028_remove_player_fees_remove_teams_fees_events_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
