# Generated by Django 4.1.1 on 2022-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0030_rename_fees_events_event_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='teams',
            name='payment_statu',
            field=models.CharField(blank=True, default='unpaid', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='payment_status',
            field=models.CharField(blank=True, default='unpaid', max_length=30, null=True),
        ),
    ]
