# Generated by Django 4.1.1 on 2022-09-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0032_rename_payment_statu_teams_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_venue',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
