# Generated by Django 4.1.1 on 2022-09-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0033_events_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='poster_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
