# Generated by Django 4.1.1 on 2022-09-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0034_events_poster_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='number_of_members_allowed',
            field=models.CharField(blank=True, default='1', max_length=300, null=True),
        ),
    ]
