# Generated by Django 4.1.1 on 2022-09-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0035_alter_events_number_of_members_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='event_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='event_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
