# Generated by Django 4.1.1 on 2022-10-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0036_player_event_id_teams_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='first_prize',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='second_prize',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='third_prize',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='college_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='college_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
