# Generated by Django 4.1.1 on 2022-10-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0037_events_first_prize_events_second_prize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='name_of_members',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
