# Generated by Django 4.1.1 on 2022-10-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0038_alter_teams_name_of_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='total_number_of_members_allowed',
            field=models.CharField(blank=True, default='1', max_length=300, null=True),
        ),
    ]
