# Generated by Django 4.1.1 on 2022-10-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0039_events_total_number_of_members_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='current_members_in_event',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
