# Generated by Django 4.1.1 on 2022-10-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0041_alter_events_current_members_in_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='enrty',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='number_of_members_allowed_in_event',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
