# Generated by Django 4.1.1 on 2022-10-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0042_events_enrty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='enrty',
            new_name='entry',
        ),
    ]
