# Generated by Django 4.1.1 on 2022-10-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0045_alter_events_current_members_in_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='entry',
            field=models.CharField(blank=True, default='1', max_length=300, null=True),
        ),
    ]
