# Generated by Django 4.1.1 on 2022-10-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0046_alter_events_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='total_number_of_members_allowed',
        ),
    ]
