# Generated by Django 4.1.1 on 2022-10-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0048_events_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='user_email',
        ),
    ]
